
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "99d"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /js
  static_dir: js

- url: /tasks/
  script: mindgraph.app
  login: admin

- url: /dist/src
  static_dir: dist/src

- url: /dist/build
  static_dir: dist/build

- url: /admin/gauth.*
  script: mindgraph.app
  login: admin
  secure: always

- url: /.*
  script: mindgraph.app

builtins:
- deferred: on

libraries:
- name: django
  version: "1.2"
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: ssl
  version: "latest"
- name: markupsafe
  version: "0.15"


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.scss$
- ^(.*/)?.*\.less$
- ^(.*/)?.*\.woff2$
- ^(.*/)?.*\.db$
- ^(.*/)?.*\.map$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules/.*$
